apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerApp
  labels:
    app: CustomerApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerApp
  template:
    metadata:
      labels:
        app: CustomerApp
    spec:
      containers:
        - name: CustomerApp
          image: username/CustomerApp:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5