server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/** 
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: hotel
          uri: http://localhost:8083
          predicates:
            - Path=/roomManagements/** 
        - id: viewPage
          uri: http://localhost:8084
          predicates:
            - Path=/reservationStatusViews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/reservations/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: hotel
          uri: http://hotel:8080
          predicates:
            - Path=/roomManagements/** 
        - id: viewPage
          uri: http://viewPage:8080
          predicates:
            - Path=/reservationStatusViews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080