server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Rental
          uri: http://localhost:8081
          predicates:
            - Path=/rentals/** 
        - id: Payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: Manage
          uri: http://localhost:8083
          predicates:
            - Path=/manages/** 
        - id: ViewPage
          uri: http://localhost:8084
          predicates:
            - Path= /rentalStatusViews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Rental
          uri: http://Rental:8080
          predicates:
            - Path=/rentals/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/payments/** 
        - id: Manage
          uri: http://Manage:8080
          predicates:
            - Path=/manages/** 
        - id: ViewPage
          uri: http://ViewPage:8080
          predicates:
            - Path= /rentalStatusViews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080