server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payment/**
        - id: roommanagement
          uri: http://localhost:8083
          predicates:
            - Path=/roommanagement/**
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins:
      #         - "*"
      #       allowedMethods:
      #         - "*"
      #       allowedHeaders:
      #         - "*"
      #       allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://user04-customer:8080
          predicates:
            - Path=/customer/**
        - id: payment
          uri: http://user04-payment:8080
          predicates:
            - Path=/payment/**
        - id: roommanagement
          uri: http://user04-roommanagement:8080
          predicates:
            - Path=/roommanagement/**
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins:
      #         - "*"
      #       allowedMethods:
      #         - "*"
      #       allowedHeaders:
      #         - "*"
      #       allowCredentials: true

server:
  port: 8080